version: "3.8"

services:
    postgres_db:
        container_name: postgres_db
        image: postgres:alpine
        restart: always
        volumes:
            - db_data:/var/lib/postgresql/data/
            - ./docker_pg_init.sh:/docker-entrypoint-initdb.d/docker_pg_init.sh
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_MULTIPLE_DATABASES:
                ${DB1_NAME},${DB1_USER},${DB1_PASSWORD}; 
                ${DB2_NAME},${DB2_USER},${DB2_PASSWORD};
                ${DB3_NAME},${DB3_USER},${DB3_PASSWORD};
        ports:
            - "5432:5432"
        networks:
            - pg_grid
    pg_admin:
        container_name: pg_admin
        image: dpage/pgadmin4
        restart: always
        volumes:
            - pgadmin_data:/var/lib/pgadmin/
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - "1234:80"
        depends_on:
            - postgres_db
        networks:
            - pg_grid
networks:
    pg_grid:
        driver: bridge
volumes:
    db_data:
    pgadmin_data:
